### ISSUE TITLE
function error

### ISSUE THREAD

**Issue by jmbelloteau** [kristerkari/stylelint-scss#109]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I'm having issue with **stylelint-scss** and plugin on a SCSS function.
A space is asked where it shouldn't.

> What CSS is needed to reproduce this issue?

```scss
@for $i from 1 through length ($breakpoints) {
    // some code
  }
```
The error disappear when I remove the space between **length** and **($breakpoints)**:

```scss
@for $i from 1 through length($breakpoints) {
    // some code
  }
```
> What stylelint configuration is needed to reproduce this issue?

```json
{
  "extends": "stylelint-config-standard",
  "plugins": [
    "stylelint-scss",
    "stylelint-order"
  ],
  "rules": {
    "color-hex-case": "lower",
    "color-hex-length": "long",
    "number-leading-zero": "never",
    "value-list-max-empty-lines": 1,
    "comment-empty-line-before": "never",
		"order/order": [
      "custom-properties",
			"declarations"
		]
  }
}
```

> Which version of stylelint are you using?

"stylelint": "^7.9.0"
"stylelint-scss": "^1.4.3"

> How are you running stylelint: CLI, PostCSS plugin, Node API?

With stylelint-webpack-plugin.

> What did you expect to happen?

I need to know how to disable the concerned rule or even better create an exception for this case.

**Comment by dryoma** [comment]
Hi @jmbelloteau 

> disable the concerned rule

The answer to that and a hint for us where to look would be you posting the exact error message ;)

**Comment by kristerkari** [comment]
@jmbelloteau This is most likely a rule that is defined in `stylelint-config-standard`, so you should have a look at the readme for that plugin.

**Comment by jimblue** [comment]
Hi @dryoma @kristerkari  !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
Hi @dryoma @kristerkari !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
Hi @dryoma @kristerkari !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
@dryoma, @kristerkari  !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

Cheers
