### ISSUE TITLE
Release new version with support stylelint@8

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#142]
Stylelint@8 was shipped, let's support :+1:

**Comment by martinwolf** [comment]
Yeah, that would be awesome. Just updated stylelint to Version 8 in one of my projects and the linting still works, but running it as a precommit hook with "Husky" doesn't work because the 7.x.x version of stylelint is used but isn't compatible with the new rules from stylelint 8.

Anyway. Would love to see the update supporting Styelelint 8. 😃

**Comment by kristerkari** [comment]
Yeah, I can release a new version with stylelint 8 support.

@evilebottnawi What would be the best way to bump stylelint version? Release a patch? Release a minor version? What about changing to use stylelint as a peer dependency? Would that break backwards compatibility?

**Comment by evilebottnawi** [comment]
@kristerkari release a major version :+1: 
@jeddy3 @davidtheclark @hudochenkov what do your think about using `stylelint` as peer dep?

**Comment by davidtheclark** [comment]
@evilebottnawi: I think that this is one of the main purposes of peer dependencies — so yes!

**Comment by giladgray** [comment]
peer dep seems correct here. 
it's the same strategy used by [tslint-react](https://github.com/palantir/tslint-react/blob/master/package.json#L24-L27), a tslint plugin package analogous to this one.

**Comment by kristerkari** [comment]
Done:
https://github.com/kristerkari/stylelint-scss/releases/tag/2.0.0
