### ISSUE TITLE
Rule-idea:space-around-operator

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#20]
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#spacearoundoperator

**Comment by kristerkari** [comment]
Thanks! I guess this could be useful for someone, so I'll add this to the next milestone.

**Comment by jeddy3** [comment]
Perhaps called `calculation-no-unspaced-operator` as "calculation" seems to be a [*thing*](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#about-rule-names) in SCSS) so it can be used in tandem with stylelint's [core rule](https://github.com/stylelint/stylelint/tree/master/src/rules/function-calc-no-unspaced-operator)

**Comment by dryoma** [comment]
@jeddy sure, no problem.

As about the rule. I am goint to make it exactly a `-no-` rule, meaning prohibiting spaces around operators seems to be no-go. At least because `$var--lol` is a valid variable name in Sass, and if we prohibit spaces we will force users to write `$var - 10px` as `$var-10px`, which would lead to a totally incorrect result.

I'd also save ourselves an effort distinguishing `calc` from all the other functions and would rather check operators inside `calc()` here as well.

**Comment by jeddy3** [comment]
> I am goint to make it exactly a -no- rule

I agree. Well reasoned.

**Comment by evilebottnawi** [comment]
i think best options: "always" and "never".

**Comment by dryoma** [comment]
@evilebottnawi with `"never"` users won't be able to write:

* `$var - 10px`; they will be forced to write it as `$var-10px`, which Sass interprets as a variable name (like in `$var-10px: #faaac0;`)
* `font-family: sans- + "serif";`; they will have to do it as `font-family: sans - + "serif";` which is compiled into `font-family: sans-+"serif";`

**Comment by evilebottnawi** [comment]
@dryoma oops, i forget ;) right rule must have `no`

**Comment by dryoma** [comment]
Some more things I'd like to bring up:

1. Make `operator` rather than `calculation` the thing here, as the rule would work with conditions and logical operations (`@if ($i == 10 and $j != 1)`) as well.
1. Users (me included) would want control over where newlines are allowed: before or after an operator. Yet I think it's best to do it in a way of eslint's [`operator-linebreak`](http://eslint.org/docs/rules/operator-linebreak). I.e. not forcing linebreaks on every instance of an operator, but just specifying where they are allowed (before of after the operator) if a used wants to set them. Also, no distinguishing on whether it is a multiline operation (just like [`function-calc-no-unspaced-operator`](http://stylelint.io/user-guide/rules/function-calc-no-unspaced-operator/) doesn't do it).
    
    So I'm thinking of a set of rules:
    * `operator-no-unspaced` - require a single whitespace on both sides of an operator;
    * `operator-no-empty-line-before` - disallow empty line before an operator;
    * `operator-no-empty-line-after` - disallow empty line after an operator;

**Comment by jeddy3** [comment]
>  Does each rule need to address indentation itself?

Nope, indentation should be the sole domain of the `indentation` rule.

Originally the `indentation` rule just ignored the indentation within function arguments and other parentheses. Now there is [an option](https://github.com/stylelint/stylelint/blob/master/src/rules/indentation/README.md#optional-options) to check. We putting it behind an option to avoid requiring a major release. With `7.0` on the horizon this behaviour might change.

> Make `operator` rather than `calculation` the thing here

That looks elegant and well-reasoned to me.

**Comment by dryoma** [comment]
Wow, totally missed those options, thanks!

**Comment by dryoma** [comment]
Published with 1.3.0.
