### ISSUE TITLE
Find unused Sass variables

### ISSUE THREAD

**Issue by MartijnCuppens** [kristerkari/stylelint-scss#276]
@XhmikosR and @Johann-S made a plugin which detects variables that aren't used: https://github.com/XhmikosR/find-unused-sass-variables

It would be nice if we can make a stylelint plugin of this. I tried to make something myself but I don't really have an idea how I should approach this and I'm afraid I'm just not experienced enough in these things to make something valuable.

I think this could be something we could definitely use in [Bootstrap](https://github.com/twbs/bootstrap).

**Comment by kristerkari** [comment]
I like the idea and I think that you have a good start for a great tool.

The idea reminds me of this eslint plugin:
https://github.com/atfzl/eslint-plugin-css-modules#readme

> I'd definitely love to see this as a rule here and drop that plugin for sure. :)

I have nothing against adding the rule to this plugin as long as the implementation can be done in a way that the perf stays good :)

Reading the files from a disk and parsing the SCSS can be fast when you have 100 files in your project, but what happens if you have thousands or tens of thousand of files?

I think it makes sense to make a proof of concept and see if the rule can be implemented so that it prints correct line numbers in correct files for the unused vars.

**Comment by kristerkari** [comment]
There was some additional discussion in #328 about this.

There are two major issues with creating a rule like this:

1) Very difficult to achieve good performance.
2) The difficulty/impossibility of correctly resolving variables:
 > In addition to performance, there's the issue of accurately resolving imports. Many applications pass load paths or custom importers to Sass which the linter won't have access to, without which accurately resolving imports to see which variables are defined in a given scope becomes essentially impossible.

That's why it instead of having a rule it makes more sense to have a script that finds unused variables:
https://github.com/XhmikosR/find-unused-sass-variables
