### ISSUE TITLE
Rule idea: at-rule-blacklist

### ISSUE THREAD

**Issue by dryoma** [kristerkari/stylelint-scss#30]
Specify a blacklist of disallowed at-rules (mainly Sass constructs like `@extend`, `@include`).

Or `at-directive-blacklist`, since `@extend` and `@include`, as I see them, are not rules at all.

The main goal is to be able to disallow extends. But making one general blacklist rule seems a better idea then one specific rule (or two rules - some people might not like mixins).

**Comment by kristerkari** [comment]
👍

**Comment by jeddy3** [comment]
Do you fancy developing this one over at stylelint as `at-rule-name-blacklist` and `at-rule-name-whitelist` because it's applicable to more than `@extend` and `@include` e.g. `@supports`, `@keyframes`, `@font-face` etc...?

[Reference](https://www.w3.org/TR/css-syntax-3/#at-rule) for the *thing* name `at-rule-name-*`.

**Comment by dryoma** [comment]
@jeddy3 that sounds even better, I'll give it a shot.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/1410
