### ISSUE TITLE
comment-no-loud

### ISSUE THREAD

**Issue by Jastos** [kristerkari/stylelint-scss#439]
comment-no-loud is not disallowing /* comments

`/* MOBILE NAV STYLES */`

`"scss/comment-no-loud": true,`

**Comment by kristerkari** [comment]
I just tested and it does give a warning for your example. Do you have something misconfigured?

**Comment by mdimovska** [comment]
I have experienced the same problem. Apart from this, the behavior of this rule was a bit weird in  other cases. You can find some examples below.
 
* **Example 1:**
With the following scss content (example1.scss):
![image](https://user-images.githubusercontent.com/6908242/73934759-65bccb80-48df-11ea-8fd3-e10e8bcece4d.png)
stylelint does not complain:
![image](https://user-images.githubusercontent.com/6908242/73934732-56d61900-48df-11ea-84d3-a322e4251ef7.png)

* **Example 2:**
With the following scss content (example2.scss):
![image](https://user-images.githubusercontent.com/6908242/73934941-bfbd9100-48df-11ea-9f05-ad460e05287b.png)
I got completely different lint errors from what I expected (it complains that I use `//` instead of `/**/`):
![image](https://user-images.githubusercontent.com/6908242/73935003-df54b980-48df-11ea-8089-1aa0bce4e672.png)
After replacing `/**/` with `//` as shown below, there were no lint errors:
![image](https://user-images.githubusercontent.com/6908242/73935056-03b09600-48e0-11ea-88dc-95cba2de1c26.png)

* **Example 3:** 
What is more weird is that when I transferred the `/**/` comments from example2.scss to example1.scss, stylelint did not complain anymore:
![image](https://user-images.githubusercontent.com/6908242/73935149-3490cb00-48e0-11ea-8e2e-cacc595bc5ea.png)
![image](https://user-images.githubusercontent.com/6908242/73935156-378bbb80-48e0-11ea-9786-c12d2d35c116.png)


I am using stylelint-config-sass-guidelines@7.0.0 (with stylelint-scss@3.14.2).

**Comment by mdimovska** [comment]
I have experienced the same problem. Apart from this, the behavior of this rule was a bit weird in  other cases. You can find some examples below.
 
* **Example 1:**
With the following scss content (example1.scss):
![image](https://user-images.githubusercontent.com/6908242/73934759-65bccb80-48df-11ea-8fd3-e10e8bcece4d.png)
stylelint does not complain:
![image](https://user-images.githubusercontent.com/6908242/73934732-56d61900-48df-11ea-84d3-a322e4251ef7.png)

* **Example 2:**
With the following scss content (example2.scss):
![image](https://user-images.githubusercontent.com/6908242/73934941-bfbd9100-48df-11ea-9f05-ad460e05287b.png)
I got completely different lint errors from what I expected (it complains that I use `//` instead of `/**/`):
![image](https://user-images.githubusercontent.com/6908242/73935003-df54b980-48df-11ea-8089-1aa0bce4e672.png)
After replacing `/**/` with `//` as shown below, there were no lint errors:
https://github.com/kristerkari/stylelint-scss/issues/439#issuecomment-582872820

* **Example 3:** 
What is more weird is that when I transferred the `/**/` comments from example2.scss to example1.scss, stylelint did not complain anymore:
![image](https://user-images.githubusercontent.com/6908242/73935149-3490cb00-48e0-11ea-8e2e-cacc595bc5ea.png)
![image](https://user-images.githubusercontent.com/6908242/73935156-378bbb80-48e0-11ea-9786-c12d2d35c116.png)


I am using stylelint-config-sass-guidelines@7.0.0 (with stylelint-scss@3.14.2).
